export const friendsReq = [
    {
      userId: 1,
      username: "user1",
      profileImage : "./friendsImg/profile1.jpg",
      firstName: "firstname1",
      lastName: "lastname1",
      email: "user@user.com",
      gender: "male",
      description: "Some description about the users",
      gallery: "Gallery for the user",
      work: "SONG1",
    },
    {
      userId: 2,
      username: "user2",
      firstName: "firstname2",
      lastName: "lastname2",
      profileImage : "./friendsImg/profile2.jpg",
      email: "user@user.com",
      gender: "female",
      description: "Some description about the users",
      gallery: "Gallery for the user",
      work: "SONG1",
    },
    {
      userId: 3,
      username: "user3",
      firstName: "firstname3",
      lastName: "lastname3",
      profileImage : "./friendsImg/profile3.jpg",
      email: "user@user.com",
      gender: "male",
      description: "Some description about the users",
      gallery: "Gallery for the user",
      work: "SONG1",
    },
  ]